### ISSUE TITLE
Cannot install with cordova-support-google-services 1.2.0

### ISSUE THREAD

**Issue by jaybloke** [chemerisuk/cordova-plugin-firebase-analytics#80]
Had to revert back to version 0.13.0 as the install chokes with cordova-support-google-services@1.2.0

```
ionic cordova plugin add cordova-support-google-services --save
cordova plugin add cordova-plugin-firebase-analytics --save
```

Gives:

```
Installing "cordova-plugin-firebase-analytics" for ios

Error during processing of action! Attempting to revert...

Failed to install 'cordova-plugin-firebase-analytics': CordovaError: Uh oh!
"/Users/Jay/dev/app/mobile/seeker/platforms/ios/App/Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m" already exists!
    at copyNewFile (/Users/Jay/dev/app/mobile/seeker/platforms/ios/cordova/lib/plugman/pluginHandlers.js:346:45)
    at installHelper (/Users/Jay/dev/app/mobile/seeker/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
    at install (/Users/Jay/dev/app/mobile/seeker/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
    at ActionStack.process (/Users/Jay/dev/app/mobile/seeker/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/Jay/dev/app/mobile/seeker/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/Jay/dev/app/mobile/seeker/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/Jay/dev/app/mobile/seeker/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/Users/Jay/Dev/app/mobile/seeker/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/Jay/Dev/app/mobile/seeker/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/Users/Jay/Dev/app/mobile/seeker/node_modules/cordova-lib/node_modules/q/q.js:787:54)

(node:18441) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Uh oh!
"/Users/Jay/dev/app/mobile/seeker/platforms/ios/app/Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m" already exists!
(node:18441) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chemerisuk** [comment]
cordova-support-google-services@1.2.0 changes in master branch only and not published yet

**Comment by zinoadidi** [comment]
Hello.
I am having similar issues.
I will like to find out if this fix has been published to NPM

Kind Regards

**Comment by manel00** [comment]
Hello! Still giving this error?
