### ISSUE TITLE
Cannot add plugin to ios

### ISSUE THREAD

**Issue by JustasKuizinas** [chemerisuk/cordova-plugin-firebase-analytics#97]
ionic cordova plugin add cordova-plugin-firebase-analytics,  fails on ios

ionic cersion: 4.1.2
cordova version: 8.0.0

Any ideas how to fix it?

```
 ionic cordova plugin add cordova-plugin-firebase-analytics --verbose
  ionic:cli-utils Terminal info: { tty: true, ci: false } +0ms
  ionic:cli-utils CLI global options: { _: [ 'cordova', 'plugin', 'add', 'cordova-plugin-firebase-analytics' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +4ms
  ionic:cli-utils:lib:project Project type from config: Ionic Angular 3 (ionic-angular) +0ms
  ionic:cli-utils Project name: undefined +172ms
  ionic:cli Context: { binPath: '/Users/user905941/.npm-global/lib/node_modules/ionic/bin/ionic', libPath: '/Users/user905941/.npm-global/lib/node_modules/ionic', execPath: '/Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/platforms/ios', version: '4.1.2' } +0ms
  ionic:cli-utils:lib:integrations:cordova:config Using config.xml: /Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/config.xml +0ms
> cordova plugin add cordova-plugin-firebase-analytics --verbose --save
No scripts found for hook "before_plugin_add".
No version specified for cordova-plugin-firebase-analytics, retrieving version from config.xml
No version for cordova-plugin-firebase-analytics saved in config.xml or package.json
Attempting to use npm info for cordova-plugin-firebase-analytics to choose a compatible release
Running command: npm view cordova-plugin-firebase-analytics --json
Command finished with error code 0: npm view,cordova-plugin-firebase-analytics,--json
npm info for cordova-plugin-firebase-analytics did not contain any engine info. Fetching latest release
Calling plugman.fetch on plugin "cordova-plugin-firebase-analytics"
saving
Running command: npm install cordova-plugin-firebase-analytics --production --save
Command finished with error code 0: npm install,cordova-plugin-firebase-analytics,--production,--save
Copying plugin "/Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/node_modules/cordova-plugin-firebase-analytics" => "/Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/plugins/cordova-plugin-firebase-analytics"
Calling plugman.install on plugin "/Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/plugins/cordova-plugin-firebase-analytics" for platform "ios
Installing "cordova-plugin-firebase-analytics" for ios
Running command: /Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/platforms/ios/cordova/version 
Command finished with error code 0: /Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/platforms/ios/cordova/version 
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-firebase-analytics on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-firebase-analytics" on ios.
PlatformApi successfully found for platform ios
Beginning processing of action stack for ios project...
Action stack processing complete.
Adding pods since the plugin contained <framework>(s) with type="podspec"
pods.json found in platforms/ios
Podfile found in platforms/ios
Set pods.json for `Firebase/Core`
Added pod line for `Firebase/Core`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Running command: pod install --verbose
==== pod install start ====

  Preparing


Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Nicehash`: (``)

Finding Podfile changes
  A Firebase
  - FirebaseMessaging

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `FirebaseAnalytics (= 4.2.0)` required by `Podfile.lock`
- `FirebaseAnalytics (~> 4.0)` required by `FirebaseMessaging (2.0.8)`
- `FirebaseAnalytics (= 5.1.1)` required by `Firebase/Core (5.6.0)`

/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/resolver.rb:461:in `handle_resolver_error'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/resolver.rb:80:in `rescue in resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/resolver.rb:72:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:771:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:768:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:79:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:242:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

Command finished with error code 1: pod install,--verbose
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:15837) UnhandledPromiseRejectionWarning: Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/user905941/Projects/Nicehash/NicehashApp/NicehashApp/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:15837) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15837) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hvaughan3** [comment]
You might try running `pod update` in the **/platform/ios/** directory. That fixes a different pod error I get at times. Have never seen this specific one.

**Comment by JustasKuizinas** [comment]
@hvaughan3 tried `pod update` still no luck

```
5-159-229-156:ios user905941$ pod update
Update all pods
Updating local specs repositories
  $ /usr/bin/git -C /Users/user905941/.cocoapods/repos/master fetch origin --progress
  remote: Enumerating objects: 15, done.        
  remote: Counting objects: 100% (15/15), done.        
  remote: Compressing objects: 100% (9/9), done.        
  remote: Total 9 (delta 6), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     c1dec5252b6..63e9b67c910  master     -> origin/master
  $ /usr/bin/git -C /Users/user905941/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/user905941/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 63e9b67c910 [Add] SubtleVolume 1.0.0

CocoaPods 1.6.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.1

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `GoogleUtilities/MethodSwizzler (~> 5.2.0)` required by `FirebaseAnalytics (5.1.1)`

Specs satisfying the `GoogleUtilities/MethodSwizzler (~> 5.2.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by chemerisuk** [comment]
Try to use the latest version of the plugin.

**Comment by YaroslavG** [comment]
@chemerisuk the error was present ion the latest version of plugin!
